# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\rai.service.v1\"\xc5\x01\n\x0b\x43hatRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12:\n\x08metadata\x18\x05 \x03(\x0b\x32(.ai.service.v1.ChatRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe2\x01\n\x0c\x43hatResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x03\x12\r\n\x05model\x18\x04 \x01(\t\x12\x33\n\x07\x63hoices\x18\x05 \x03(\x0b\x32\".ai.service.v1.ChatResponse.Choice\x12#\n\x05usage\x18\x06 \x01(\x0b\x32\x14.ai.service.v1.Usage\x1a<\n\x06\x43hoice\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\"O\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\x42PZNhttps://github.com/KyleKichulYun/Lightweight-AI-Model-Serving-Router/gen/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNhttps://github.com/KyleKichulYun/Lightweight-AI-Model-Serving-Router/gen/proto'
  _globals['_CHATREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATREQUEST']._serialized_start=39
  _globals['_CHATREQUEST']._serialized_end=236
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_start=189
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_end=236
  _globals['_CHATRESPONSE']._serialized_start=239
  _globals['_CHATRESPONSE']._serialized_end=465
  _globals['_CHATRESPONSE_CHOICE']._serialized_start=405
  _globals['_CHATRESPONSE_CHOICE']._serialized_end=465
  _globals['_USAGE']._serialized_start=467
  _globals['_USAGE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
